---
docker_tag: election-orchestra-wtools
base_image: election-orchestra
apt_repositories:
eorchestra_dest: /election-orchestra
vfork_dest: /vfork
certs_dest: /srv/certs/selfsigned
apt_packages:
pip_packages:
required_directories:
git_repositories:
  agora-tools:
    name: https://github.com/agoravoting/agora-tools.git
    branch: master
    dest: /agora-tools
env_vars:

