---
- name: This playbook builds an Authority server docker image
  hosts: all
  vars_files:
    - config.yml
  roles:
  - role: election-orchestra
  - { role: docker-build, tag: "{{ docker_tag.election_orchestra }}" version: "{{ election_orchestra.version }}"}
  - role: agora-tools
  - { role: docker-build, tag: "{{ docker_tag.agora_tools }}"  version: "{{ agora_tools.version }}" }
