---
  - command: which docker
    ignore_errors: yes
    register: docker_installed

  - name: install apt packages
    apt: "name='{{ item }}' state=present update_cache=yes"
    with_items:
      - python-pip

  - name: install docker-py
    pip: name=docker-py version=1.1.0

  - name: Update Packages
    apt: update_cache=yes
    when: docker_installed|failed

  - name: Download docker package
    get_url: url=https://get.docker.com/ dest=/install_docker.sh mode=0755
    when: docker_installed|failed

  - name: Install docker
    command: /install_docker.sh
    when: docker_installed|failed
