---
  - name: Include image version if specified
    set_fact: docker.image_name="{{ docker.image_name }}:{{ DOCKER_IMAGE_VERSION }}"
    when: DOCKER_IMAGE_VERSION is defined

  - name: Application container
    docker:
      name: eorchestra
      image: "{{ docker.image_name }}"
      state: reloaded
      pull: always
      volumes:
        - "{{ host.keys_path }}:{{ docker.keys_path}}"
        - "{{ host.certs_path }}:{{ docker.certs_path}}"
        - "{{ host.tests_path }}:{{ docker.tests_path}}"
        - "{{ host.logs_path }}:{{ docker.logs_path}}"
      ports:
        - "{{ PORT }}: {{ docker.port }}"
        - "{{ host.vfork_port }}: {{ docker.vfork_port }}"
        - "{{ host.vfork_hint_port }}: {{ docker.vfork_hint_port }}"
        - "{{ host.eotest_port }}: {{ docker.eotest_port }}"
      expose:
        - "{{ PORT }}"
        - "{{ host.vfork_port }}"
        - "{{ host.vfork_hint_port }}"
        - "{{ host.eotest_port }}"
      env:
        PORT: "{{ PORT }}"
        HOST: "{{ HOST }}"
        PUBLICIP: "{{ PUBLIC_IP }}"
        PRIVATEIP: "{{ PRIVATE_IP }}"
        KEYSTORE_PASS: "{{ KEYSTORE_PASS }}"
        DB_USER: "{{ db_user }}"
        DB_NAME: "{{ db_name }}"
        DB_HOST: "{{ DB_HOST }}"
        DB_PASSWORD: "{{ DB_PASSWORD }}"
        CERT_CA: "{{ CERT_CA }}"
        CERT_NAME: "{{ CERT_NAME }}"
        CERT_KEY: "{{ CERT_KEY }}"
        AUTH_MEMBERS: "{{ AUTH_MEMBERS }}"
