---
  db_user: eorchestra
  db_name: eorchestra
  db_port: 5432
  cidr_block: 172.17.0.0/16
  PRIVATE_IP: '{{ ansible_eth1["ipv4"]["address"] }}'
  PUBLIC_IP: '{{ PRIVATE_IP }}'
  DB_HOST: '{{ PRIVATE_IP }}'
  postgres:
    main_conf: /etc/postgresql/9.3/main/postgresql.conf
    hba_conf: /etc/postgresql/9.3/main/pg_hba.conf
  host:
    keys_path: /home/vagrant/keys
    certs_path: /home/vagrant/certs
    tests_path: /home/vagrant/eotests
    port: 443
    vfork_port: 4081
    vfork_hint_port: 8081
  docker:
    keys_path: /root/keys
    certs_path: /srv/certs/selfsigned
    tests_path: /srv/eotests
    port: 443
    vfork_port: 4081
    vfork_hint_port: 8081
